### PR TITLE
chore: Rename branches master->release, nightly->main

### PR DESCRIPTION
**Pull request by DawoudSheraz**
Part of overhangio/tutor#1096, updates the cookiecutter GA to use updated branch names

### CODE REVIEW

**Comment by CodeWithEmad** [comment]
@DawoudSheraz did we forget about this repo? I still see the master branch.
image

**Comment by DawoudSheraz** [comment]
I thought about updating this but considering this is a cookie-cutter and not an actual plugin, it made sense to leave it as master.

**Comment by CodeWithEmad** [comment]
I'm okay with the name "master" for the cookiecutter. I just thought you decided on release and forgot about changing this :)

**Comment by kdmccormick** [comment]
I think master is good, since this doesn't follow the main+release system that the other repos do.

**Pull request merged**
